In [1]:
# Single line comment

#=

Multi
line
Comment

=#

### Basic syntax, variables, data types

In [2]:
# Print on console
println("Hello, World!")

Hello, World!


In [3]:
# String interpolation
x = 1
println("Value of x: $x") # Using $ operator

Value of x: 1


In [4]:
# Basic arithmetic
a = 10
b = 3

println("Sum: $(a + b)")
println("Difference: $(a - b)")
println("Multiplication: $(a * b)")
println("Quotient: $(a / b)")
println("Exponential: $(a ^ b)")
println("Integer division: $(a ÷ b)") # \div TAB
println("Modulus: $(a % b)")

Sum: 13
Difference: 7
Multiplication: 30
Quotient: 3.3333333333333335
Exponential: 1000
Integer division: 3
Modulus: 1


In [5]:
# Type inspection
x = 1
println("Type of x: $(typeof(x))") # Integer 64-bit

x = 1.0
println("Type of x: $(typeof(x))") # Float 64-bit

# isa function
println("x is a float: $(x isa AbstractFloat)")
println("x is an integer: $(x isa Integer)")

Type of x: Int64
Type of x: Float64
x is a float: true
x is an integer: false


In [6]:
# Mathematical constants
println("Type of π: ", typeof(π)) # \pi TAB
println("π approximation: ", Float64(π)) # Casting
println("Long π: ", big(π)) # Arbitrary-precision floating-point number
println("sin(π/2): ", sin(π))

println("\n")

println("Type of ℯ: ", typeof(ℯ)) # \euler TAB
println("ℯ approximation: ", Float64(ℯ)) # Casting
println("Long ℯ: ", big(ℯ)) # Arbitrary-precision floating-point number
println("ln(ℯ): ", log(ℯ))

Type of π: Irrational{:π}
π approximation: 3.141592653589793
Long π: 3.141592653589793238462643383279502884197169399375105820974944592307816406286198
sin(π/2): 0.0


Type of ℯ: Irrational{:ℯ}
ℯ approximation: 2.718281828459045
Long ℯ: 2.718281828459045235360287471352662497757247093699959574966967627724076630353555
ln(ℯ): 1


In [7]:
# Rational numbers
x = 2 // 3
println("x is rational: ", x)
println("x type: ", typeof(x))
println("x type (Int32): ", typeof(Int32(2) // Int32(3)))

println("\n")

a = 1 // 5
println("a + x rational form: ", a + x) # The result remains rational
println("a + x value Float16: ", Float16(a + x))
println("a + x value Float32: ", Float32(a + x))
println("a + x value Float64: ", Float64(a + x)) # Or just using the float() method
println("a + x value BigFloat: ", BigFloat(a + x)) # Or just use the big() method

x is rational: 2//3
x type: Rational{Int64}
x type (Int32): Rational{Int32}


a + x rational form: 13//15
a + x value Float16: 0.8667
a + x value Float32: 0.8666667
a + x value Float64: 0.8666666666666667
a + x value BigFloat: 0.8666666666666666666666666666666666666666666666666666666666666666666666666666678


In [8]:
# Complex numbers
x = 3 + 4im
println("x int type: ", typeof(x))

x = 3.0 + 4.0im # Float64
println("x float type: ", typeof(x))

println("\n")

println("Real part of x: ", real(x))
println("Imaginary part of x: ", imag(x))
println("Conjugate of x: ", conj(x))
println("Magnitude of x: ", abs(x))
println("Angle of x: ", angle(x)) # Rad

x int type: Complex{Int64}
x float type: ComplexF64


Real part of x: 3.0
Imaginary part of x: 4.0
Conjugate of x: 3.0 - 4.0im
Magnitude of x: 5.0
Angle of x: 0.9272952180016122


In [9]:
# Strings
str = "Julia programming"
println("Type: ", typeof(str))
println("\n")

println("First element: ", str[1])
println("Last element: ", str[end])
println("Length of the string: ", length(str))
println("Type of a character: ", typeof(str[2]))

# String concatenation
str = "String 1" * " " * "String 2" # Using the * operator
println(str)

str = string("String 1", " ", "String 2") # Using the string method()
print(str)

Type: String


First element: J
Last element: g
Length of the string: 17
Type of a character: Char
String 1 String 2
String 1 String 2

### Control flow

In [10]:
# if-else
x = - 0

if x > 0
    println("x is positive")
elseif x < 0
    println("x is negative")
else
    println("x is zero")
end

x is zero


In [11]:
# While
i = 2
n = 1

while i <= 6
    n *= i
    i += 1
end

println("Factorial of 6: ", n)


Factorial of 6: 720


In [12]:
# For cycle
for j in 2:2:20 # Start, Step, End
    println(j)
end

2
4
6
8
10
12
14
16
18
20


In [13]:
# Loop control rules
for j in 1:10

    if j == 5
        continue
    end
    if j == 7
        break
    end

println(j)
end

println("\nj = 5 skipped")
println("Cycle stopped at j = 7")

1
2
3
4
6

j = 5 skipped
Cycle stopped at j = 7


In [14]:
# Nested loop 1
for i in 1:5
    for j in 1:5
        println("$i × $j = $(i * j)")
    end
    print("\n")
end

1 × 1 = 1
1 × 2 = 2
1 × 3 = 3
1 × 4 = 4
1 × 5 = 5

2 × 1 = 2
2 × 2 = 4
2 × 3 = 6
2 × 4 = 8
2 × 5 = 10

3 × 1 = 3
3 × 2 = 6
3 × 3 = 9
3 × 4 = 12
3 × 5 = 15

4 × 1 = 4
4 × 2 = 8
4 × 3 = 12
4 × 4 = 16
4 × 5 = 20

5 × 1 = 5
5 × 2 = 10
5 × 3 = 15
5 × 4 = 20
5 × 5 = 25



In [15]:
# Nested loop 2
for i in 1:5, j in 1:5 # i and j on a single line
    println("$i × $j = $(i * j)")
end

1 × 1 = 1
1 × 2 = 2
1 × 3 = 3
1 × 4 = 4
1 × 5 = 5
2 × 1 = 2
2 × 2 = 4
2 × 3 = 6
2 × 4 = 8
2 × 5 = 10
3 × 1 = 3
3 × 2 = 6
3 × 3 = 9
3 × 4 = 12
3 × 5 = 15
4 × 1 = 4
4 × 2 = 8
4 × 3 = 12
4 × 4 = 16
4 × 5 = 20
5 × 1 = 5
5 × 2 = 10
5 × 3 = 15
5 × 4 = 20
5 × 5 = 25


### Data Structures

In [16]:
# Arrays
arr = [1, 3, 5, 7, 9] # 1D array
println(arr)

arr = [1 5 8; 2 1 9] # Matrix 2 × 3
arr

[1, 3, 5, 7, 9]


2×3 Matrix{Int64}:
 1  5  8
 2  1  9

In [17]:
arr = [10, 20, 30, 40, 50, 60]
println(arr)

# Array indexing & slicing
println("First element: ", arr[1])
println("Last element: ", arr[end])
println("Subarray [20, 30, 40]: ", arr[2:4])
println("Subarray odd: ", arr[2:2:end]) # Start index, step, stop index

println("\n")

arr = [1 2 3; 4 5 6; 7 8 9] # 3 × 3 matrix
println(arr)

# Matrix indexing & slicing
println("First element of the first row/col: ", arr[1, 1])
println("First element of the last row: ", arr[end, 1])
println("First element of the second col: ", arr[1, 2])
println("First row: ", arr[1, :])
println("First col: ", arr[:, 1])
println("Submatrix: ", arr[1:2, 1:2])

[10, 20, 30, 40, 50, 60]
First element: 10
Last element: 60
Subarray [20, 30, 40]: [20, 30, 40]
Subarray odd: [20, 40, 60]


[1 2 3; 4 5 6; 7 8 9]
First element of the first row/col: 1
First element of the last row: 7
First element of the second col: 2
First row: [1, 2, 3]
First col: [1, 4, 7]
Submatrix: [1 2; 4 5]


In [18]:
# Another way to create matrices directly (easier)
arr = [1 2 3
       4 5 6
       7 8 9]
arr

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [19]:
# Array comprehension
arr = [x ^ 2 for x in 1:10] # Vector
println(arr)

arr = [a * b for a in 1:5, b in 1:5] # Matrix
println(arr)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[1 2 3 4 5; 2 4 6 8 10; 3 6 9 12 15; 4 8 12 16 20; 5 10 15 20 25]


In [20]:
# Array assignment
arr = ones(10) # ones() method
println("Original array: ", arr)

arr[1] = 2
println("After the assignment: ", arr) # 2 has been promoted to float64

Original array: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
After the assignment: [2.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]


In [21]:
# Some built-in methods
println("Random vector: ", rand(Float32, 10))
println("Random matrix: ", rand(Float32, 4, 4))
println("\n")

println("Vector of zero: ", zeros(Float32, 10))
println("Matrix of zero: ", zeros(Float32, (3, 3)))
println("\n")

println("Vector of ones: ", ones(Float32, 10))
println("Matrix of ones: ", ones(Float32, (2, 2)))
println("\n")

println("Vector of 5s: ", fill(5, 10)) # Int64
println("Matrix of 5s: ", fill(5.0, (3, 3))) # Float64
println("\n")

println("Reshaping: ", reshape(rand(9), (3, 3))) # Float64
println("Flattening: ", vec(reshape(rand(9), (3, 3)))) # Float64

Random vector: Float32[0.85303414, 0.43460333, 0.85960114, 0.7996919, 0.141128, 0.43275118, 0.6308038, 0.7459598, 0.34301072, 0.51108354]
Random matrix: Float32[0.3667131 0.6720138 0.15676683 0.80189055; 0.44236314 0.5964576 0.18268919 0.59661007; 0.90017486 0.0006120205 0.88041896 0.37267596; 0.92257273 0.76865363 0.5011809 0.9000786]


Vector of zero: Float32[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
Matrix of zero: Float32[0.0 0.0 0.0; 0.0 0.0 0.0; 0.0 0.0 0.0]


Vector of ones: Float32[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
Matrix of ones: Float32[1.0 1.0; 1.0 1.0]


Vector of 5s: [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]
Matrix of 5s: [5.0 5.0 5.0; 5.0 5.0 5.0; 5.0 5.0 5.0]


Reshaping: [0.07546707839360078 0.4507218525443879 0.965273357502535; 0.7709432262815983 0.054939370675585075 0.4722765564660063; 0.3281610264500029 0.0003726791560708653 0.45825162575084855]
Flattening: [0.6537357893045563, 0.5895110536870931, 0.6311385447607221, 0.17260125474248433, 0.70425208808424

In [22]:
# Transponse
arr = Int16[i - j ^ 2 + i * j - 1 for i in 1:3, j in 1:3] # Int16

display(arr)
display(arr') # Transponse

3×3 Matrix{Int16}:
 0  -2  -6
 2   1  -2
 4   4   2

3×3 adjoint(::Matrix{Int16}) with eltype Int16:
  0   2  4
 -2   1  4
 -6  -2  2

In [23]:
# Array concatenations
A = [i for i in 1:5, j in 1:5]
B = [i ^ 3 for i in 1:5, j in 1:5]

display([A; B]) # Vertical concatenation (method: vcat(A, B))
display([A B]) # Horizontal concatenation (method: hcat(A, B))

10×5 Matrix{Int64}:
   1    1    1    1    1
   2    2    2    2    2
   3    3    3    3    3
   4    4    4    4    4
   5    5    5    5    5
   1    1    1    1    1
   8    8    8    8    8
  27   27   27   27   27
  64   64   64   64   64
 125  125  125  125  125

5×10 Matrix{Int64}:
 1  1  1  1  1    1    1    1    1    1
 2  2  2  2  2    8    8    8    8    8
 3  3  3  3  3   27   27   27   27   27
 4  4  4  4  4   64   64   64   64   64
 5  5  5  5  5  125  125  125  125  125

In [24]:
# Some operations
println("A + B: ", A + B)
println("A * B: ", A * B) # Matrix multiplication
println("A .* B: ", A .* B) # Element-wise multiplication
println("sin(A): ", sin.(A)) # Use '.' for element-wise operations

A + B: [2 2 2 2 2; 10 10 10 10 10; 30 30 30 30 30; 68 68 68 68 68; 130 130 130 130 130]
A * B: [225 225 225 225 225; 450 450 450 450 450; 675 675 675 675 675; 900 900 900 900 900; 1125 1125 1125 1125 1125]
A .* B: [1 1 1 1 1; 16 16 16 16 16; 81 81 81 81 81; 256 256 256 256 256; 625 625 625 625 625]
sin(A): [0.8414709848078965 0.8414709848078965 0.8414709848078965 0.8414709848078965 0.8414709848078965; 0.9092974268256817 0.9092974268256817 0.9092974268256817 0.9092974268256817 0.9092974268256817; 0.1411200080598672 0.1411200080598672 0.1411200080598672 0.1411200080598672 0.1411200080598672; -0.7568024953079282 -0.7568024953079282 -0.7568024953079282 -0.7568024953079282 -0.7568024953079282; -0.9589242746631385 -0.9589242746631385 -0.9589242746631385 -0.9589242746631385 -0.9589242746631385]


In [25]:
# Searching
println(findall(j -> j > 2, A)) # Find all elements of A > 2
println(filter(j -> j > 2, A)) # Take all elements of A > 2

CartesianIndex{2}[CartesianIndex(3, 1), CartesianIndex(4, 1), CartesianIndex(5, 1), CartesianIndex(3, 2), CartesianIndex(4, 2), CartesianIndex(5, 2), CartesianIndex(3, 3), CartesianIndex(4, 3), CartesianIndex(5, 3), CartesianIndex(3, 4), CartesianIndex(4, 4), CartesianIndex(5, 4), CartesianIndex(3, 5), CartesianIndex(4, 5), CartesianIndex(5, 5)]
[3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5, 3, 4, 5]


In [26]:
# Tuples, they cannot be modified
t = (1, 2, 3)
t = 1, 2, 3
t = tuple(1, 2, 3)
t

(1, 2, 3)

In [27]:
# Accessing and properties
println("First element: ", t[1])
println("Last element: ", t[end])
println("Length of t: ", length(t))
println("Type of t: ", eltype(t))

First element: 1
Last element: 3
Length of t: 3
Type of t: Int64


In [28]:
# Unzip
a, b, c = t

(1, 2, 3)

In [29]:
# NamedTuples
nt = (a = 1, b = 2, c = 3)
println(nt)
println("\n")

# Accessing
println("a: ", nt.a)
println("b: ", nt.b)
println("c: ", nt.c)
println("\n")

println("Keys: ", keys(nt))
println("Values: ", values(nt))

(a = 1, b = 2, c = 3)


a: 1
b: 2
c: 3


Keys: (:a, :b, :c)
Values: (1, 2, 3)


In [30]:
# Merging NamedTuples
nt2 = (d = 4, e = 5, f = 6)

merge(nt, nt2)

(a = 1, b = 2, c = 3, d = 4, e = 5, f = 6)

In [31]:
# Dictionaries
d = Dict("a" => 1, "b" => 2, "c" => 3) # keys as strings, values as Int64

Dict{String, Int64} with 3 entries:
  "c" => 3
  "b" => 2
  "a" => 1

In [32]:
# Access: d["j"]
for j in d
    println(j)
end

# Modify values or add new elements
d["a"] = 100
d["d"] = 101

println(d)

"c" => 3
"b" => 2
"a" => 1
Dict("c" => 3, "b" => 2, "a" => 100, "d" => 101)


### Functions

In [33]:
# Basic
function Hello()
    println("Hello, World!")
end

Hello()

Hello, World!


In [34]:
# Arguments
function multiply(a, b)
    return a * b
end

# Another expression equivalent:
multiply(a, b) = a * b

println("Int64 × Int64: ", multiply(10, 5))
println("Int64 × Int32: ", multiply(10, Int32(5))) # The result is an Int64
println("Float32 × Float16: ", multiply(Float32(10), Float16(5))) # The result is a Float32

Int64 × Int64: 50
Int64 × Int32: 50
Float32 × Float16: 50.0


In [35]:
# Default Arguments
e = ℯ
function power(exponent, base = e)
    return Float32(base ^ exponent)
end

println("5^2: ", power(5, 2))
println("e^2: ", power(2))
println("\n")

function area(r, precision = 2)
    return round(π * r ^ 2; digits = precision) # round() method
end

println(area(2))
println(area(2, 10))

5^2: 32.0
e^2: 7.389056


12.57
12.5663706144


In [36]:
# Multiple return
function division(a::Int, b::Int) # Specify types of arguments
    return (a ÷ b, a % b) # Tuple
end

q, r = division(10, 3)

println("10 // 3 is equal to $q with reminder of $r")

10 // 3 is equal to 3 with reminder of 1


In [37]:
# ...() Splat operator
function sumf(args...)
    total = 0
    for arg in args
        total += arg
    end

    return total
end

println(sumf(1, 2, 3))
println(sumf(1, 2, 3, 4, 5, 6))
println(sumf(10, 99))

6
21
109


In [38]:
# Anonymus functions
cube = x -> x ^ 3 # 1 input
square = (x, y) -> x ^ 2 + y ^ 2 # 2 inputs

println(cube(9))
println(square(cos(2), sin(2)))

729
1.0


In [39]:
# Apply a function to an array using '.'
arr = [i ^ 2 for i in 1:10]
println(cube.(arr))

# Another way: using the map() method
map(cube, arr)

[1, 64, 729, 4096, 15625, 46656, 117649, 262144, 531441, 1000000]


10-element Vector{Int64}:
       1
      64
     729
    4096
   15625
   46656
  117649
  262144
  531441
 1000000

In [40]:
# Multiple dispatch
function describe(x::Int)
    println("It's an integer")
end

function describe(x::String)
    println("It's a string")
end

function describe(x::Float64)
    println("It's a float")
end

describe(1)
describe(1.0)
describe("Hi")

It's an integer
It's a float
It's a string


In [41]:
# Multiple dispatch of known operators
Base.:+(s1::String, s2::String) = string(s1, s2)

"Hello, " + "World!" # Operator + has a new dispatch

"Hello, World!"

In [42]:
# See dispatches of a method
methods(sum)

# 10 methods for generic function "sum" from Base:
  [1] sum(r::StepRangeLen{<:Any, <:Base.TwicePrecision, <:Base.TwicePrecision})
     @ twiceprecision.jl:603
  [2] sum(r::StepRangeLen)
     @ twiceprecision.jl:588
  [3] sum(r::AbstractRange{<:Real})
     @ range.jl:1405
  [4] sum(arr::AbstractArray{BigFloat})
     @ Base.MPFR mpfr.jl:848
  [5] sum(a::AbstractArray{Bool}; kw...)
     @ reduce.jl:562
  [6] sum(arr::Union{Tuple{BigInt, Vararg{BigInt}}, AbstractArray{BigInt}})
     @ Base.GMP gmp.jl:679
  [7] sum(a::AbstractArray; dims, kw...)
     @ reducedim.jl:982
  [8] sum(f, a::AbstractArray; dims, kw...)
     @ reducedim.jl:983
  [9] sum(f, a; kw...)
     @ reduce.jl:532
 [10] sum(a; kw...)
     @ reduce.jl:561

### Metaprogramming

In [43]:
# AST - Abstract Syntax Tree
ex = :(a + b)
println(ex)

# Substitutions
a = 10
b = 10
ex = :($a + $b)
println("Expression: ", ex)
println("Value: ", eval(ex))

a + b
Expression: 10 + 10
Value: 20


In [44]:
# Macros
arr = Int32[i for i in 1:1000000]
@time sum(arr) # Time macro, built-in

  0.069875 seconds (59.08 k allocations: 2.964 MiB, 99.04% compilation time)


500000500000

### Miscellaneous

In [45]:
# Fibonacci sequence iteratively
function F(n)
  
    if n == 0
        return 0
    elseif n == 1
        return 1
    end
    
    first = 0
    second = 1
    next = 0
    
    # Start from 2 since we already handled 0 and 1
    for j in 2:n
        next = first + second
        first = second
        second = next
    end
    
    return second
end

[F(j) for j in 0:50]

51-element Vector{Int64}:
           0
           1
           1
           2
           3
           5
           8
          13
          21
          34
           ⋮
   267914296
   433494437
   701408733
  1134903170
  1836311903
  2971215073
  4807526976
  7778742049
 12586269025

In [46]:
# Using the direct formula
function F2(n)
    a = 0.5 * (1 + sqrt(5.0))
    b = 0.5 * (1 - sqrt(5.0))

    return Int64(round((a ^ n - b ^ n) / sqrt(5.0)))
end

[F2(j) for j in 0:50]

51-element Vector{Int64}:
           0
           1
           1
           2
           3
           5
           8
          13
          21
          34
           ⋮
   267914296
   433494437
   701408733
  1134903170
  1836311903
  2971215073
  4807526976
  7778742049
 12586269025

In [47]:
# FizzBuzz
for j in 1:100
    if j % 15 == 0
        println("FizzBuzz")
    elseif j % 3 == 0
        println("Fizz")
    elseif j % 5 == 0
        println("Buzz")
    else
        println(j)
    end
end

1
2
Fizz
4
Buzz
Fizz
7
8
Fizz
Buzz
11
Fizz
13
14
FizzBuzz
16
17
Fizz
19
Buzz
Fizz
22
23
Fizz
Buzz
26
Fizz
28
29
FizzBuzz
31
32
Fizz
34
Buzz
Fizz
37
38
Fizz
Buzz
41
Fizz
43
44
FizzBuzz
46
47
Fizz
49
Buzz
Fizz
52
53
Fizz
Buzz
56
Fizz
58
59
FizzBuzz
61
62
Fizz
64
Buzz
Fizz
67
68
Fizz
Buzz
71
Fizz
73
74
FizzBuzz
76
77
Fizz
79
Buzz
Fizz
82
83
Fizz
Buzz
86
Fizz
88
89
FizzBuzz
91
92
Fizz
94
Buzz
Fizz
97
98
Fizz
Buzz


In [48]:
# Check if a number is prime
function is_prime(N::Integer)
    
    (N == 2 || N == 1) && return true
    N % 2 == 0 && return false

    for i in 3:2:isqrt(N)
        N % i == 0 && return false
    end

    return true
end

is_prime(47)

true