## Matrix Decomposition in R

We're going to perform some matrix decompositions by using the *pracma* R library

```r
# Importing pracma
> library(pracma)

# Defining a vector
> vec <- c(1:25)
> vec
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25

# Defining the matrix
> A <- matrix(data = -vec, nrow = 5, ncol = 5, byrow = TRUE)
> A
     [,1] [,2] [,3] [,4] [,5]
[1,]   -1   -2   -3   -4   -5
[2,]   -6   -7   -8   -9  -10
[3,]  -11  -12  -13  -14  -15
[4,]  -16  -17  -18  -19  -20
[5,]  -21  -22  -23  -24  -25

# Computing e raised to the matrix A
> A <- expm(A)
> A
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891

# LU decomposition
> A_LU <- lu(A)

# Extracting L
> L <-A_LU$L
> L
            [,1]        [,2]       [,3]       [,4] [,5]
[1,]  1.00000000  0.00000000  0.0000000  0.0000000    0
[2,]  0.50580116  1.00000000  0.0000000  0.0000000    0
[3,]  0.05747549 -0.02784383  1.0000000  0.0000000    0
[4,] -0.39085017 -0.27680051 -0.3468983  1.0000000    0
[5,] -0.83917589 -0.52575672 -0.5479972 -0.9364204    1

# Extracting U
> U <- A_LU$U
> U
         [,1]      [,2]       [,3]       [,4]          [,5]
[1,] 21.79926 13.156150 5.51304500 -2.1300610 -9.773166e+00
[2,]  0.00000  1.283883 0.06196444 -0.1599547 -3.818733e-01
[3,]  0.00000  0.000000 0.87275334 -0.2266504 -3.260533e-01
[4,]  0.00000  0.000000 0.00000000  0.5926621 -4.677767e-01
[5,]  0.00000  0.000000 0.00000000  0.0000000  1.435089e-06

# Proof: A = LU
> L %*% U
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891
> A
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891

# QR decomposition
> A_QR <- qr(A)

# Computing Q
> Q <- qr.Q(A_QR)
> Q
            [,1]       [,2]       [,3]        [,4]      [,5]
[1,] -0.68743245  0.5467528  0.2625988  0.12288567 0.3800513
[2,] -0.34770413 -0.8215951  0.1669214  0.07811223 0.4124550
[3,] -0.03951052  0.0620014 -0.8919551  0.03333924 0.4448588
[4,]  0.26868309  0.0902682  0.2022488 -0.80683068 0.4772638
[5,]  0.57687674  0.1185345  0.2582454  0.57158581 0.5096683

# Computing R
> R <-qr.R(A_QR)
> R
          [,1]      [,2]        [,3]       [,4]         [,5]
[1,] -31.71112 -20.06798 -8.45637088  3.1552389 1.476685e+01
[2,]   0.00000  -1.16914 -0.08633496  0.1411405 3.686152e-01
[3,]   0.00000   0.00000 -0.96319902  0.2266828 3.783568e-01
[4,]   0.00000   0.00000  0.00000000 -0.7953972 6.277923e-01
[5,]   0.00000   0.00000  0.00000000  0.0000000 7.314195e-07

# Proof: A = QR
> Q %*% R
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891
> A
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891

# Proof: Q is orthogonal
> det(Q)
[1] 1
> inv(Q)
           [,1]        [,2]        [,3]       [,4]      [,5]
[1,] -0.6874325 -0.34770413 -0.03951052  0.2686831 0.5768767
[2,]  0.5467528 -0.82159507  0.06200140  0.0902682 0.1185345
[3,]  0.2625988  0.16692135 -0.89195511  0.2022488 0.2582454
[4,]  0.1228857  0.07811223  0.03333924 -0.8068307 0.5715858
[5,]  0.3800513  0.41245499  0.44485878  0.4772638 0.5096683
> t(Q)
           [,1]        [,2]        [,3]       [,4]      [,5]
[1,] -0.6874325 -0.34770413 -0.03951052  0.2686831 0.5768767
[2,]  0.5467528 -0.82159507  0.06200140  0.0902682 0.1185345
[3,]  0.2625988  0.16692135 -0.89195511  0.2022488 0.2582454
[4,]  0.1228857  0.07811223  0.03333924 -0.8068307 0.5715858
[5,]  0.3800513  0.41245499  0.44485878  0.4772638 0.5096683

# Eigenvalues decomposition
> A_eig <- eigen(A)
> M <- A_eig$vectors
> M
            [,1]       [,2]        [,3]          [,4]      [,5]
[1,] -0.67495283  0.3849134  0.08428975  1.567008e-08 0.1079747
[2,] -0.36038970 -0.4456035 -0.61888347 -5.000000e-01 0.2527752
[3,] -0.04582658 -0.4322984  0.60040532  5.000000e-01 0.3975755
[4,]  0.26873656  0.6617520  0.31868094  5.000000e-01 0.5423746
[5,]  0.58329969 -0.1687649 -0.38449239 -5.000000e-01 0.6871751

# Proof: A = M D M^-1
> D <- diag(A_eig$values)
> D
         [,1] [,2] [,3] [,4]        [,5]
[1,] 38.49241    0    0    0 0.00000e+00
[2,]  0.00000    1    0    0 0.00000e+00
[3,]  0.00000    0    1    0 0.00000e+00
[4,]  0.00000    0    0    1 0.00000e+00
[5,]  0.00000    0    0    0 5.39721e-07

> M %*% D %*% inv(M)
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891
> A
           [,1]       [,2]      [,3]      [,4]      [,5]
[1,]  21.799256  13.156150  5.513045 -2.130061 -9.773166
[2,]  11.026089   7.938279  2.850469 -1.237342 -5.325152
[3,]   1.252923   0.720408  1.187893 -0.344623 -0.877138
[4,]  -8.520243  -5.497463 -2.474683  1.548097  3.570877
[5,] -18.293410 -11.715334 -5.137259  1.440816  9.018891
```

